### ISSUE TITLE
Is this primitive really working only on Python 3.5?

### ISSUE THREAD

**Issue by mitar** [usc-isi-i2/dsbox-overfit-detector#2]
Or does it support also Python 3.6? If so, could you add python3.6 to the primitive annotation?

**Comment by mmichelsonIF** [comment]
Good catch. In fact, the TA1 Pipeline uses the Python3.6 docker image.

I updated the Primitive annotation JSON and submitted a merge request to JPL.

**Comment by mitar** [comment]
Thanks!
